### ISSUE TITLE
Add a deprecation notice (and recommendation for mozjpeg) to the readme

### ISSUE THREAD

**Issue by shinnn** [kud/jpegrescan#18]
I totally agree on https://github.com/kud/jpegrescan/issues/17#issuecomment-61581457:

> i suspect jpegrescan is nearing obsolescence in the wake of mozjpeg which is under active development and compressing jpegs tiny percents more than jpegrescan already.

The deprecation notice is useful for developers looking for a really good image optimizer.

**Comment by kud** [comment]
Do a PR. ;)

**Comment by olizilla** [comment]
I think this project still has value... @pornel's https://github.com/pornel/ImageOptim app uses it to losslessly compress jpegs after a lossy compression first pass. So I'd run a mozjpeg, then a jpegrescan to further reduce the filesize.

**Comment by pornel** [comment]
ImageOptim will be moved to mozjpeg soon

**Comment by shinnn** [comment]
Thanks :) https://github.com/kud/jpegrescan/commit/3d4c080477ae5eb0c6d12fd30eef0638dbee5629
