### ISSUE TITLE
Another release tag?

### ISSUE THREAD

**Issue by olizilla** [kud/jpegrescan#19]
This project still works well, and has had some fixes since the last release. Other projects re-package it: 
https://github.com/watilde/jpegrescan-bin

See: https://github.com/watilde/jpegrescan-bin/blob/master/lib/index.js

But as they rely on tags, they're not getting the benefit of those fixes.

**Comment by pornel** [comment]
OK, I've created a tag, although I'd suggest everybody to migrate to mozjpeg.
