### ISSUE TITLE
Check that the file is JPEG?

### ISSUE THREAD

**Issue by zvezdochiot** [kud/jpegrescan#26]
If the file is PNG with the jpg extension, the output is a file of zero length without warning.

**Comment by zvezdochiot** [comment]
```sh
$ cat file.jpg | head -c 10 | tail -c 4
JFIF
```

**Comment by kornelski** [comment]
I recommend switching to MozJPEG's jpegtran, which performs the check.

**Comment by zvezdochiot** [comment]
Yes. But! JpegRescan does not require mozjpeg. It looks like eliminating a competitor!
